parameters:
#    simples_erp_main.example.class: SimplesErp\Bundle\MainBundle\Example

services:
#    simples_erp_main.example:
#        class: %simples_erp_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
